training:
  epochs: 72
  mixed_precision: true
  max_norm: 0.1
  ema:
    name: exp_decay
    decay: 0.9999
    beta: 2000
  optimizer:
    name: adamw
    lr: 1e-4
    betas: [0.9, 0.999]
    weight_decay: 0.0001
  scheduler:
    name: step
    iters_per_phase: 10000
    gamma: 0.1
    end_epoch: 0
